import Link from "next/link";
import { AdminPage, AdminShell } from "@/components/admin/admin-shell";
import { InspectionForm } from "@/components/admin/lifecycle-forms";
import { getAdminReturn } from "@/lib/admin/lifecycle";
import { requirePageAdmin } from "@/lib/auth/server";

export const dynamic = "force-dynamic";
export default async function AdminReturnDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const admin = await requirePageAdmin(); const item = await getAdminReturn((await params).id); const known = new Map(item.inspections.map((inspection) => [inspection.rentalAllocationId, inspection]));
  const rows = item.rental.allocations.map((allocation) => { const inspection = known.get(allocation.id); return { allocationId: allocation.id, code: allocation.inventoryUnit.inventoryCode, product: allocation.inventoryUnit.product.name, condition: inspection?.condition ?? "NOT_ASSESSED", maintenanceType: inspection?.maintenanceType ?? "", notes: inspection?.notes ?? "" }; });
  return <AdminShell adminName={admin.name ?? admin.email}><AdminPage title="Return inspection" description="Inspect each physical unit independently before it re-enters circulation."><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_340px]"><section className="border border-[#d5c4ac] bg-[#fffdf8] p-6"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm text-[#68584a]">{item.rental.customer.name ?? item.rental.customer.email}</p><p className="mt-1 text-xs text-[#665548]">{item.rental.startAt.toLocaleDateString("en-IN")} → {item.rental.endAt.toLocaleDateString("en-IN")}</p></div><span className="text-xs uppercase tracking-[0.12em] text-[#6f4c2f]">{item.status}</span></div><div className="mt-8"><InspectionForm returnId={item.id} rows={rows} /></div></section><aside className="h-fit border border-[#d5c4ac] bg-[#fffdf8] p-6"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#6f4c2f]">Return record</p><dl className="mt-5 space-y-4 text-sm"><div><dt className="text-[#665548]">Received</dt><dd className="mt-1">{item.receivedAt?.toLocaleString("en-IN") ?? "Not yet received"}</dd></div><div><dt className="text-[#665548]">Overall condition</dt><dd className="mt-1">{item.condition}</dd></div><div><dt className="text-[#665548]">Notes</dt><dd className="mt-1 whitespace-pre-wrap">{item.notes || "—"}</dd></div></dl>{item.rental.order && <Link href={`/admin/orders/${item.rental.order.id}`} className="mt-7 block text-sm text-[#5f4630] underline underline-offset-4">View order {item.rental.order.orderNumber} →</Link>}</aside></div></AdminPage></AdminShell>;
}
