import Link from "next/link";
import { AdminPage, AdminShell } from "@/components/admin/admin-shell";
import { getAdminCategories, getAdminProducts } from "@/lib/admin/service";
import { requirePageAdmin } from "@/lib/auth/server";

export const dynamic = "force-dynamic";

export default async function AdminProductsPage({ searchParams }: { searchParams: Promise<{ search?: string; status?: string; categoryId?: string }> }) {
  const user = await requirePageAdmin(); const query = await searchParams; const [result, categories] = await Promise.all([getAdminProducts({ search: query.search, status: query.status as "DRAFT" | "ACTIVE" | "ARCHIVED" | undefined, categoryId: query.categoryId }), getAdminCategories()]);
  return <AdminShell adminName={user.name ?? user.email}><AdminPage title="Products" description="Manage catalogue products without deleting historical references."><div className="mt-8 flex flex-wrap items-end justify-between gap-4"><form className="flex flex-wrap gap-2"><input name="search" defaultValue={query.search} placeholder="Search name or slug" className="border border-[#cdbb9f] bg-[#fffdf8] px-3 py-2 text-sm" /><label className="sr-only" htmlFor="filter-status">Status filter</label><select id="filter-status" name="status" defaultValue={query.status ?? ""} className="border border-[#cdbb9f] bg-[#fffdf8] px-3 py-2 text-sm"><option value="">All statuses</option><option>ACTIVE</option><option>DRAFT</option><option>ARCHIVED</option></select><label className="sr-only" htmlFor="filter-category">Category filter</label><select id="filter-category" name="categoryId" defaultValue={query.categoryId ?? ""} className="border border-[#cdbb9f] bg-[#fffdf8] px-3 py-2 text-sm"><option value="">All categories</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select><button className="border border-[#6b4b30] px-4 py-2 text-sm text-[#5f4630]">Filter</button></form><Link href="/admin/products/new" className="bg-[#5f4630] px-4 py-2 text-sm font-medium text-[#fffdf8]">New product</Link></div><div className="mt-8 overflow-x-auto border border-[#d5c4ac] bg-[#fffdf8]" tabIndex={0} aria-label="Scrollable content"><table className="w-full min-w-[780px] text-left text-sm"><thead className="border-b border-[#d5c4ac] bg-[#eadfce] text-xs uppercase tracking-[0.12em] text-[#68584a]"><tr><th className="p-4">Product</th><th className="p-4">Category</th><th className="p-4">Capabilities</th><th className="p-4">Inventory</th><th className="p-4">Status</th><th className="p-4">Actions</th></tr></thead><tbody className="divide-y divide-[#dfd2be]">{result.items.map((product) => <tr key={product.id}><td className="p-4"><Link href={`/admin/products/${product.id}`} className="font-medium text-[#5f4630] underline underline-offset-4">{product.name}</Link><p className="mt-1 text-xs text-[#665548]">{product.slug}</p></td><td className="p-4">{product.category.name}</td><td className="p-4 text-xs">{product.purchasable ? "Buy" : ""}{product.purchasable && product.rentable ? " · " : ""}{product.rentable ? "Rent" : ""}</td><td className="p-4">{product._count.inventoryUnits}</td><td className="p-4">{product.status}</td><td className="p-4"><Link href={`/admin/products/${product.id}`} className="text-[#5f4630] underline underline-offset-4">Edit</Link></td></tr>)}</tbody></table>{result.items.length === 0 && <p className="p-8 text-sm text-[#665548]">No products match these filters.</p>}</div><p className="mt-4 text-xs text-[#665548]">Showing page {result.page} of {Math.max(result.pages, 1)} · {result.total} products</p></AdminPage></AdminShell>;
}

