import Link from "next/link";
import { notFound } from "next/navigation";
import { AccountFrame } from "@/components/account/account-ui";
import { getCustomerCustomOrder } from "@/lib/custom-orders/service";
import { formatMoney } from "@/lib/pricing/engine";
import { requirePageUser } from "@/lib/auth/server";

export const dynamic = "force-dynamic";
export default async function CustomerCustomOrderDetailPage({ params }: { params: Promise<{ id: string }> }) { const user = await requirePageUser("/account/custom-orders"); const request = await getCustomerCustomOrder(user.id, (await params).id); if (!request) notFound(); return <AccountFrame title={request.eventType} intro="Your custom request is separate from a confirmed order or quotation."><div className="mt-8 flex flex-wrap items-center gap-3"><span className="border border-[#cdbb9f] bg-[#f7f2e9] px-3 py-2 text-xs uppercase tracking-[0.14em] text-[#6c4b30]">{request.status.replaceAll("_", " ")}</span><span className="text-sm text-[#665548]">Submitted {request.createdAt.toLocaleDateString("en-IN")}</span></div><div className="mt-8 grid gap-10 lg:grid-cols-[1fr_320px]"><section className="border-t border-[#cdbb9f] pt-6"><p className="eyebrow">Requirements</p><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-[#5e4b3a]">{request.requirements}</p>{request.referenceFileUrl && <p className="mt-6 text-sm"><a href={request.referenceFileUrl} target="_blank" rel="noreferrer" className="text-[#5f4630] underline underline-offset-4">Open reference link →</a></p>}</section><aside className="h-fit border border-[#d5c4ac] bg-[#fffdf8] p-6"><p className="eyebrow">Event details</p><dl className="mt-5 space-y-4 text-sm"><div><dt className="text-[#665548]">Event date</dt><dd className="mt-1">{request.eventDate?.toLocaleDateString("en-IN") ?? "To be confirmed"}</dd></div><div><dt className="text-[#665548]">Guest count</dt><dd className="mt-1">{request.guestCount ?? "Not supplied"}</dd></div><div><dt className="text-[#665548]">Working budget</dt><dd className="mt-1">{request.budget ? formatMoney(Number(request.budget), request.currency) : "Not supplied"}</dd></div></dl><Link href="/account/custom-orders" className="nav-link mt-8 inline-block text-sm">Back to custom requests →</Link></aside></div></AccountFrame>; }
