import Link from "next/link";
import { signOut } from "@/auth";
import type { ReactNode } from "react";

const adminLinks = [["Dashboard", "/admin"], ["Products", "/admin/products"], ["Categories", "/admin/categories"], ["Inventory", "/admin/inventory"], ["Orders", "/admin/orders"], ["Rentals", "/admin/rentals"], ["Returns", "/admin/returns"], ["Maintenance", "/admin/maintenance"], ["Custom requests", "/admin/custom-orders"]] as const;

export function AdminShell({ children, adminName }: { children: ReactNode; adminName: string }) {
  return <div className="min-h-screen bg-[#efe7da] text-[#332a22]"><aside className="fixed inset-y-0 left-0 z-30 hidden w-64 border-r border-[#d5c4ac] bg-[#332a22] p-6 text-[#fffaf0] lg:block"><Link href="/admin" className="font-serif text-2xl">Waste Weavers</Link><p className="mt-1 text-xs uppercase tracking-[0.2em] text-[#d8b995]">Operations</p><nav className="mt-10 grid gap-1 text-sm" aria-label="Admin navigation">{adminLinks.map(([label, href]) => <Link key={href} href={href} className="px-3 py-2.5 text-[#d9cabb] transition hover:bg-[#5f4630] hover:text-[#fffaf0]">{label}</Link>)}</nav><div className="absolute bottom-6 left-6 right-6 border-t border-[#6a5847] pt-5"><p className="text-xs text-[#d9cabb]">{adminName}</p><form action={async () => { "use server"; await signOut({ redirectTo: "/" }); }} className="mt-3"><button type="submit" className="text-xs text-[#f0cda8] underline underline-offset-4">Log out</button></form></div></aside><div className="lg:pl-64"><header className="border-b border-[#d5c4ac] bg-[#f7f2e9] px-5 py-4 sm:px-8"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[0.2em] text-[#6f4c2f]">Admin operations</p><p className="mt-1 text-sm text-[#68584a]">{adminName}</p></div><details className="relative lg:hidden"><summary className="cursor-pointer list-none border border-[#6b4b30] px-3 py-2 text-sm text-[#5f4630]">Menu</summary><nav className="absolute right-0 z-20 mt-2 grid min-w-52 border border-[#dfd2be] bg-[#fffdf8] p-2 text-sm shadow-xl">{adminLinks.map(([label, href]) => <Link key={href} href={href} className="px-3 py-2.5 hover:bg-[#eadfce]">{label}</Link>)}</nav></details></div></header>{children}</div></div>;
}

export function AdminPage({ children, title, description }: { children: ReactNode; title: string; description?: string }) { return <main className="mx-auto max-w-[1440px] px-5 py-8 sm:px-8 sm:py-10"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#6f4c2f]">Operations</p><h1 className="mt-2 font-serif text-4xl tracking-[-0.03em]">{title}</h1>{description && <p className="mt-2 max-w-2xl text-sm leading-6 text-[#68584a]">{description}</p>}</div>{children}</main>; }
