"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

type Metric = { metricType: string; value: string; unit: string; description: string };
const emptyMetric = (): Metric => ({ metricType: "TEXTILE_WASTE_DIVERTED", value: "", unit: "kg", description: "" });

export function ImpactMetricsEditor({ productId, initial }: { productId: string; initial: Metric[] }) {
  const router = useRouter(); const [metrics, setMetrics] = useState(initial); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  function update(index: number, field: keyof Metric, value: string) { setMetrics((current) => current.map((metric, metricIndex) => metricIndex === index ? { ...metric, [field]: value } : metric)); }
  async function save() { setBusy(true); setMessage(null); try { const response = await fetch(`/api/admin/products/${productId}/impact`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ metrics: metrics.filter((metric) => metric.value.trim()) }) }); const result = await response.json(); if (!response.ok) throw new Error(result.message ?? "Impact metrics could not be saved."); setMessage("Impact record saved."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Impact metrics could not be saved."); } finally { setBusy(false); } }
  return <section className="mt-8 border border-[#d5c4ac] bg-[#fffdf8] p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#6f4c2f]">Impact record</p><h2 className="mt-2 font-serif text-2xl">Explicit product metrics</h2><p className="mt-2 text-xs leading-5 text-[#68584a]">Supported types are textile waste diverted and reuse-cycle target. No CO₂ or water conversions.</p></div><button type="button" onClick={() => setMetrics((current) => [...current, emptyMetric()])} className="border border-[#6b4b30] px-3 py-2 text-xs text-[#5f4630]">Add metric</button></div><div className="mt-5 space-y-4">{metrics.map((metric, index) => <div key={`${index}-${metric.metricType}`} className="grid gap-3 border-t border-[#dfd2be] pt-4 sm:grid-cols-[1.3fr_0.7fr_0.5fr_auto]"><select value={metric.metricType} onChange={(event) => update(index, "metricType", event.target.value)} className="border border-[#cdbb9f] bg-[#fffdf8] px-2 py-2 text-sm"><option value="TEXTILE_WASTE_DIVERTED">Textile waste diverted</option><option value="REUSE_CYCLES_TARGET">Reuse cycles target</option></select><input value={metric.value} onChange={(event) => update(index, "value", event.target.value)} placeholder="Value" className="border border-[#cdbb9f] bg-transparent px-2 py-2 text-sm" /><input value={metric.unit} onChange={(event) => update(index, "unit", event.target.value)} placeholder="Unit" className="border border-[#cdbb9f] bg-transparent px-2 py-2 text-sm" /><button type="button" onClick={() => setMetrics((current) => current.filter((_, metricIndex) => metricIndex !== index))} className="text-left text-xs text-[#7c332a] underline underline-offset-4">Remove</button><textarea value={metric.description} onChange={(event) => update(index, "description", event.target.value)} placeholder="Description / methodology note" rows={2} className="sm:col-span-4 border border-[#cdbb9f] bg-transparent p-2 text-sm" /></div>)}{metrics.length === 0 && <p className="text-sm text-[#68584a]">No metrics recorded.</p>}</div><div className="mt-5 flex items-center gap-4"><button type="button" onClick={save} disabled={busy} className="bg-[#5f4630] px-4 py-2 text-sm font-medium text-[#fffdf8] disabled:opacity-60">{busy ? "Saving…" : "Save impact record"}</button>{message && <p className="text-sm text-[#5e4b3a]" role="status">{message}</p>}</div></section>;
}
