"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";

export function ReceiveReturnForm({ rentalId }: { rentalId: string }) {
  const router = useRouter(); const [notes, setNotes] = useState(""); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function submit() { setBusy(true); setMessage(null); try { const response = await fetch("/api/admin/returns", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rentalId, notes }) }); const result = await response.json(); if (!response.ok) throw new Error(result.message ?? "Return could not be received."); setMessage("Return received and sent to inspection."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Return could not be received."); } finally { setBusy(false); } }
  return <div className="mt-4 space-y-3"><textarea value={notes} onChange={(event) => setNotes(event.target.value)} rows={2} placeholder="Collection or receiving notes" className="w-full border border-[#cdbb9f] bg-transparent p-2 text-sm" /><button type="button" onClick={submit} disabled={busy} className="bg-[#5f4630] px-4 py-2 text-sm font-medium text-[#fffdf8] disabled:opacity-60">{busy ? "Receiving…" : "Receive return"}</button>{message && <p className="text-sm text-[#5e4b3a]" role="status">{message}</p>}</div>;
}

type InspectionRow = { allocationId: string; code: string; product: string; condition: string; maintenanceType: string; notes: string };
export function InspectionForm({ returnId, rows }: { returnId: string; rows: InspectionRow[] }) {
  const router = useRouter(); const [values, setValues] = useState(rows); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  function update(index: number, field: keyof InspectionRow, value: string) { setValues((current) => current.map((row, rowIndex) => rowIndex === index ? { ...row, [field]: value } : row)); }
  async function submit() { setBusy(true); setMessage(null); try { const response = await fetch(`/api/admin/returns/${returnId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ inspections: values.map(({ allocationId, condition, maintenanceType, notes }) => ({ allocationId, condition, maintenanceType: maintenanceType || null, notes: notes || null })) }) }); const result = await response.json(); if (!response.ok) throw new Error(result.message ?? "Inspection could not be saved."); setMessage("Inspection saved."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Inspection could not be saved."); } finally { setBusy(false); } }
  return <div className="space-y-5">{values.map((row, index) => <div key={row.allocationId} className="border-t border-[#dfd2be] pt-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-mono text-xs text-[#6d5139]">{row.code}</p><p className="mt-1 text-sm font-medium">{row.product}</p></div><select value={row.condition} onChange={(event) => update(index, "condition", event.target.value)} className="border border-[#cdbb9f] bg-[#fffdf8] px-2 py-2 text-sm"><option value="GOOD">Good — available</option><option value="NEEDS_MAINTENANCE">Needs maintenance</option><option value="DAMAGED">Damaged</option><option value="RETIRED">Retired</option></select></div>{row.condition === "NEEDS_MAINTENANCE" && <select value={row.maintenanceType} onChange={(event) => update(index, "maintenanceType", event.target.value)} className="mt-3 w-full border border-[#cdbb9f] bg-[#fffdf8] px-2 py-2 text-sm"><option value="">Select maintenance type</option><option value="CLEANING">Cleaning</option><option value="REPAIR">Repair</option><option value="REFURBISHMENT">Refurbishment</option></select>}<textarea value={row.notes} onChange={(event) => update(index, "notes", event.target.value)} rows={2} placeholder="Inspection notes" className="mt-3 w-full border border-[#cdbb9f] bg-transparent p-2 text-sm" /></div>)}<button type="button" onClick={submit} disabled={busy} className="bg-[#5f4630] px-4 py-2 text-sm font-medium text-[#fffdf8] disabled:opacity-60">{busy ? "Saving…" : "Save inspection"}</button>{message && <p className="text-sm text-[#5e4b3a]" role="status">{message}</p>}</div>;
}

export function MaintenanceStatusForm({ id, status, condition }: { id: string; status: string; condition: string }) {
  const router = useRouter(); const [nextStatus, setNextStatus] = useState(status); const [nextCondition, setNextCondition] = useState(condition); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function submit() { setBusy(true); setMessage(null); try { const response = await fetch(`/api/admin/maintenance/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: nextStatus, condition: nextCondition }) }); const result = await response.json(); if (!response.ok) throw new Error(result.message ?? "Maintenance could not be updated."); setMessage("Updated."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Maintenance could not be updated."); } finally { setBusy(false); } }
  return <div className="flex flex-wrap items-center gap-2"><select value={nextStatus} onChange={(event) => setNextStatus(event.target.value)} className="border border-[#cdbb9f] bg-[#fffdf8] px-2 py-1 text-xs"><option>PENDING</option><option>IN_PROGRESS</option><option>COMPLETED</option><option>CANCELLED</option></select><select value={nextCondition} onChange={(event) => setNextCondition(event.target.value)} className="border border-[#cdbb9f] bg-[#fffdf8] px-2 py-1 text-xs"><option>NEW</option><option>GOOD</option><option>FAIR</option><option>DAMAGED</option></select><button type="button" onClick={submit} disabled={busy || (nextStatus === status && nextCondition === condition)} className="border border-[#6b4b30] px-2 py-1 text-xs text-[#5f4630] disabled:opacity-50">{busy ? "Saving…" : "Save"}</button>{message && <span className="text-xs" role="status">{message}</span>}</div>;
}
