import { NextResponse } from "next/server";
import { z } from "zod";
import { archiveAdminProduct, getAdminProduct, updateAdminProduct, AdminServiceError } from "@/lib/admin/service";
import { AuthenticationRequiredError, AuthorizationDeniedError } from "@/lib/auth/server";

const schema = z.object({ name: z.string().min(1), slug: z.string().min(1), shortDescription: z.string().optional(), description: z.string().min(1), categoryId: z.string().min(1), purchasePrice: z.string().nullable().optional(), purchasable: z.boolean(), rentable: z.boolean(), rentalPricingConfig: z.object({ strategy: z.enum(["PER_DAY", "PER_24_HOURS"]).optional(), rate: z.string().optional(), currency: z.string().optional() }).nullable().optional(), material: z.string().optional(), dimensions: z.string().optional(), weight: z.string().nullable().optional(), color: z.string().optional(), status: z.enum(["DRAFT", "ACTIVE", "ARCHIVED"]), images: z.array(z.object({ url: z.string().url().or(z.string().startsWith("/")), altText: z.string().min(1), sortOrder: z.number().int().min(0) })).optional() });
function failure(error: unknown) { if (error instanceof AuthenticationRequiredError) return NextResponse.json({ message: "Please sign in." }, { status: 401 }); if (error instanceof AuthorizationDeniedError) return NextResponse.json({ message: "Admin access is required." }, { status: 403 }); if (error instanceof AdminServiceError) return NextResponse.json({ code: error.code, message: error.message }, { status: error.code === "NOT_FOUND" ? 404 : 422 }); return NextResponse.json({ message: "Product operation failed." }, { status: 500 }); }
export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) { try { return NextResponse.json(await getAdminProduct((await params).id)); } catch (error) { return failure(error); } }
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { try { const parsed = schema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ message: "Product details are invalid." }, { status: 400 }); return NextResponse.json(await updateAdminProduct((await params).id, parsed.data)); } catch (error) { return failure(error); } }
export async function DELETE(_request: Request, { params }: { params: Promise<{ id: string }> }) { try { return NextResponse.json(await archiveAdminProduct((await params).id)); } catch (error) { return failure(error); } }
