import Link from "next/link";
import { AdminPage, AdminShell } from "@/components/admin/admin-shell";
import { ReceiveReturnForm } from "@/components/admin/lifecycle-forms";
import { getAdminReturns, getAdminReturnsAwaitingAction } from "@/lib/admin/lifecycle";
import { requirePageAdmin } from "@/lib/auth/server";

export const dynamic = "force-dynamic";
export default async function AdminReturnsPage() {
  const admin = await requirePageAdmin();
  const [awaiting, returns] = await Promise.all([getAdminReturnsAwaitingAction(), getAdminReturns()]);
  return <AdminShell adminName={admin.name ?? admin.email}><AdminPage title="Returns" description="Receive physical units, then record a separate inspection outcome for every allocated item."><div className="mt-8 grid gap-8 xl:grid-cols-[1fr_1fr]"><section><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#6f4c2f]">Awaiting return</p><div className="mt-4 space-y-4">{awaiting.length === 0 ? <div className="border border-dashed border-[#cdbb9f] p-6 text-sm text-[#68584a]">No rentals are currently awaiting return.</div> : awaiting.map((rental) => <article key={rental.id} className="border border-[#d5c4ac] bg-[#fffdf8] p-5"><div className="flex flex-wrap justify-between gap-3"><div><Link href={`/admin/rentals/${rental.id}`} className="font-medium text-[#5f4630] underline underline-offset-4">{rental.order?.orderNumber ?? rental.id}</Link><p className="mt-1 text-sm">{rental.customer.name ?? rental.customer.email}</p><p className="mt-1 text-xs text-[#665548]">Ends {rental.endAt.toLocaleDateString("en-IN")} · {rental.allocations.length} unit(s)</p></div><span className="text-xs uppercase tracking-[0.12em] text-[#6f4c2f]">{rental.status}</span></div>{rental.return ? <p className="mt-4 text-sm text-[#68584a]">Return received {rental.return.receivedAt?.toLocaleDateString("en-IN") ?? "—"}</p> : <ReceiveReturnForm rentalId={rental.id} />}</article>)}</div></section><section><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#6f4c2f]">Return records</p><div className="mt-4 space-y-4">{returns.length === 0 ? <div className="border border-dashed border-[#cdbb9f] p-6 text-sm text-[#68584a]">No return records yet.</div> : returns.map((item) => <Link key={item.id} href={`/admin/returns/${item.id}`} className="block border border-[#d5c4ac] bg-[#fffdf8] p-5 transition hover:border-[#6b4b30]"><div className="flex justify-between gap-3"><div><p className="font-medium">{item.rental.order?.orderNumber ?? item.rental.id}</p><p className="mt-1 text-sm text-[#68584a]">{item.rental.customer.name ?? item.rental.customer.email}</p></div><span className="text-xs uppercase tracking-[0.12em] text-[#6f4c2f]">{item.status}</span></div><p className="mt-3 text-xs text-[#665548]">{item.rental.allocations.length} allocated unit(s) · {item.inspections.length} inspected</p></Link>)}</div></section></div></AdminPage></AdminShell>;
}
