"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";

export function CustomOrderForm() {
  const router = useRouter(); const [form, setForm] = useState({ eventType: "Wedding", eventDate: "", guestCount: "", requirements: "", budget: "", referenceFileUrl: "" }); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  function update(field: keyof typeof form, value: string) { setForm((current) => ({ ...current, [field]: value })); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setMessage(null); try { const response = await fetch("/api/custom-orders", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, guestCount: form.guestCount ? Number(form.guestCount) : null, budget: form.budget || null, eventDate: form.eventDate || null, referenceFileUrl: form.referenceFileUrl || null }) }); const result = await response.json(); if (!response.ok) throw new Error(result.message ?? "Request could not be submitted."); router.push(`/account/custom-orders/${result.id}`); } catch (error) { setMessage(error instanceof Error ? error.message : "Request could not be submitted."); } finally { setBusy(false); } }
  return <form onSubmit={submit} className="border border-[#d5c4ac] bg-[#fffdf8] p-6 sm:p-8"><div className="grid gap-6 sm:grid-cols-2"><label className="text-sm font-medium">Event type<select value={form.eventType} onChange={(event) => update("eventType", event.target.value)} className="mt-2 w-full border-b border-[#cdbb9f] bg-transparent px-1 py-2"><option>Wedding</option><option>Corporate</option><option>Birthday</option><option>Festival</option><option>Other</option></select></label><label className="text-sm font-medium">Event date<input type="date" value={form.eventDate} onChange={(event) => update("eventDate", event.target.value)} className="mt-2 w-full border-b border-[#cdbb9f] bg-transparent px-1 py-2" /></label><label className="text-sm font-medium">Guest count <span className="font-normal text-[#665548]">(optional)</span><input type="number" min="1" max="100000" value={form.guestCount} onChange={(event) => update("guestCount", event.target.value)} className="mt-2 w-full border-b border-[#cdbb9f] bg-transparent px-1 py-2" /></label><label className="text-sm font-medium">Working budget in INR <span className="font-normal text-[#665548]">(optional)</span><input type="number" min="0" step="0.01" value={form.budget} onChange={(event) => update("budget", event.target.value)} className="mt-2 w-full border-b border-[#cdbb9f] bg-transparent px-1 py-2" /></label><label className="text-sm font-medium sm:col-span-2">What are you imagining?<textarea required minLength={10} maxLength={5000} value={form.requirements} onChange={(event) => update("requirements", event.target.value)} rows={7} placeholder="Tell us about the setting, palette, décor needs, and anything you already know." className="mt-2 w-full border border-[#cdbb9f] bg-transparent p-3 leading-6 outline-none focus:border-[#5f4630]" /></label><label className="text-sm font-medium sm:col-span-2">Reference image or file link <span className="font-normal text-[#665548]">(optional HTTPS URL or local reference path)</span><input value={form.referenceFileUrl} onChange={(event) => update("referenceFileUrl", event.target.value)} placeholder="https://… or /references/…" className="mt-2 w-full border-b border-[#cdbb9f] bg-transparent px-1 py-2" /></label></div><div className="mt-8 flex flex-wrap items-center gap-4"><button type="submit" disabled={busy} className="bg-[#5f4630] px-5 py-3 text-sm font-medium text-[#fffdf8] disabled:opacity-60">{busy ? "Submitting…" : "Submit custom request"}</button><p className="text-xs text-[#665548]">This is a request for review, not a confirmed quotation or booking.</p></div>{message && <p className="mt-4 text-sm text-[#7c332a]" role="alert">{message}</p>}</form>;
}
